=== FrenchYeti/ffv4php/Rulessets/rulesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- **************************************************
DO NOT EDIT THIS FILE
GB MICHEL , 20313-06-11 
*************************************************** -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>		
				<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
				<xs:element name="reference" type="referencetype"></xs:element>
	    		<xs:element name="mimetypes" type="mimettype" minOccurs="0"></xs:element>
	    		<xs:element name="info" type="infotype" maxOccurs="1"></xs:element>
	    		<xs:element name="asserts" type="assertstype" maxOccurs="1"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element> 
    
    <xs:complexType name="infotype">
    	<xs:sequence>
    		<xs:element name="author" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
    		<xs:element name="since" type="xs:date" minOccurs="0" maxOccurs="1"></xs:element>
    		<xs:element name="version" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
    		<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="mimettype">
    	<xs:sequence>
    		<xs:element name="mime" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="referencetype">
    	<xs:sequence>
    		<xs:element name="reftype" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="refid" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="specid" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="spectitle" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="comment" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="structtype">
	  <xs:simpleContent>
	    <xs:extension base="xs:string">
	      <xs:attribute name="start" type="xs:string"/>
	      <xs:attribute name="length" type="xs:string"/>
	      <xs:attribute name="endianess" type="xs:string"/>
	      <xs:attribute name="stop" type="xs:string"/>
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType> 	
    
    <xs:complexType name="iftype">
	  <xs:simpleContent>
	    <xs:extension base="xs:string">
	      <xs:attribute name="condition" type="xs:string"/>
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType>
        
    <xs:complexType name="controltype">
    	<xs:sequence>
    		<xs:element name="if" type="iftype" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		<xs:element name="default" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="controllerstype">
    	<xs:sequence>
    		<xs:element name="control-true" type="controltype" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="control-false" type="controltype" minOccurs="1" maxOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
	
    <xs:complexType name="asserttype">
    	<xs:sequence>	
    		<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="struct" type="structtype" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="message" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		<xs:element name="controllers" type="controllerstype" minOccurs="0" maxOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
	<xs:complexType name="assertstype">
    	<xs:sequence>
    		<xs:element name="ids" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
    		<xs:element name="assert" type="asserttype" minOccurs="1" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== FrenchYeti/ffv4php/Rulessets/png/RFC2083_4-1-3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../rulesSchema.xsd">
	<reference>
	    <reftype>RFC</reftype>
	    <refid>2083</refid>    
	    <specid>4.7</specid>
	    <spectitle>IDAT Chunk</spectitle>
	    <comment>
	    Validation of IDAT chunk 
	    </comment>
	</reference>
	<info>
	    <author>Georges-B. MICHEL</author>
	    <version>1.0</version>
	    <description></description>
	</info>
	<asserts>
		<ids>3</ids>
	    <assert>
	    	<id>1</id>
	        <struct start="0" endianess="big">@size:uint32::() / {'PLTE'} / [ [ @:uint8::(0>256) ;;; 3 ] ;;; ]</struct>
	        <message>Invalid IDAT Chunk format</message>  
	        <controllers>
	        	<control-true>
	        		<default>4.1</default>
	        	</control-true> 
	        	<control-false>
	        		<default>EXIT</default>
	        	</control-false>
	        </controllers>		   
	    </assert>
	</asserts>	
</rule>

=== FrenchYeti/ffv4php/Rulessets/png/RFC2083_4-1-1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../rulesSchema.xsd">
	<reference>
	    <reftype>RFC</reftype>
	    <refid>2083</refid>    
	    <specid>4.7</specid>
	    <spectitle>IHDR Chunk</spectitle>
	    <comment>
	    Validation of IHDR chunk 
	    </comment>
	</reference>
	<info>
	    <author>Georges-B. MICHEL</author>
	    <version>1.0</version>
	    <description></description>
	</info>
	<asserts>
		<ids>2</ids>
	    <assert> 
	    	<id>1</id>           
	        <struct start="0" endianess="big">{"0000000dh".'IHDR'} / @width:uint32::(!0) / @height:uint32::(!0) / @:uint8::(1,2,4,8,16) / @color:uint8::(0,2,3,4,6) / @:uint8::(0) / @:uint8::(0) / @:uint8::(0,1)</struct>
	        <message>Invalid IHDR Chunk format</message>  
	        <controllers>
	        	<control-true>
	        		<if condition="((@width = 1) and (@height = 1)) or (@color > 1)">3.2</if>
	        		<if condition="@color = 3">3.1</if>
	        		<default>4.1</default>
	        	</control-true> 
	        	<control-false>
	        		<default>EXIT</default>
	        	</control-false>
	        </controllers>	        	 
	    </assert>
	</asserts>
</rule>

=== FrenchYeti/ffv4php/Rulessets/png/RFC2083_12-11.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../rulesSchema.xsd">
	<reference>
	    <reftype>RFC</reftype>
	    <refid>2083</refid>    
	    <specid>12.11</specid>
	    <spectitle>Signature</spectitle>
	    <comment>
	    Validation of file's signature based on 8 firsts bytes    
	    </comment>
	</reference>
	<info>
	    <author>Georges-B. MICHEL</author>
	    <version>1.0</version>
	    <description></description>
	</info>
	<asserts>
		<ids>1</ids>
	    <assert>    
	    	<id>1</id>        
	        <struct start="0" endianess="big">{"89504e470d0a1a0ah"}</struct>
	        <message>Invalid signature</message>  
	        <controllers>
	        	<control-true>
	        		<default>2.1</default>
	        	</control-true> 
	        	<control-false>
	        		<default>EXIT</default>
	        	</control-false>
	        </controllers>	        
	    </assert>
	</asserts>
</rule>

=== FrenchYeti/ffv4php/Rulessets/png/RFC2083_4-1-2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../rulesSchema.xsd">
	<reference>
	    <reftype>RFC</reftype>
	    <refid>2083</refid>    
	    <specid>4.1.4</specid>
	    <spectitle>IEND Chunk</spectitle>
	    <comment>
	    Validation of IEND chunk 
	    </comment>
	</reference>
	<info>
	    <author>Georges-B. MICHEL</author>
	    <version>1.0</version>
	    <description></description>
	</info>
	<asserts>
		<ids>4</ids>
	    <assert>
	    	<id>1</id>            
	        <struct start="-8" endianess="big">{'IEND'}</struct>
	        <message>Invalid IEND Chunk format</message>  
	        <controllers>
	        	<control-true>
	        		<default>END</default>
	        	</control-true> 
	        	<control-false>
	        		<default>EXIT</default>
	        	</control-false>
	        </controllers>	 
	    </assert>
	</asserts>
</rule>
